language: cpp

compiler:
  - gcc
  - clang

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted"
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      libpango-1.0-0
      qtbase5-dev
      qtdeclarative5-dev
      qttools5-dev-tools
      qtdeclarative5-dev-tools
      qt5-default
      qtdeclarative5-qtquick2-plugin
      qtdeclarative5-test-plugin
      python-mako
      cmake
      ninja-build
      zlib1g-dev
      gcc
      g++
      perl

script:
  - . tools/setup_env.sh
  - tools/build_dependencies.py -j4 --shared
  - tools/bootstrap.py
  - ninja -j4 -C out
  - cd out && ctest -VV
  - cd ${TRAVIS_BUILD_DIR} && tools/run_test.py
