language: cpp

compiler:
  - gcc
  - clang

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421 1E9377A2BA9EF27F 3B4FE6ACC0B21F32
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      libpango-1.0-0
      qtbase5-dev
      qtdeclarative5-dev
      qttools5-dev-tools
      qtdeclarative5-dev-tools
      qt5-default
      qtdeclarative5-qtquick2-plugin
      qtdeclarative5-test-plugin
      python-simplejson
      python-mako
      libgoogle-perftools-dev
      curl
      unzip
      build-essential
      cmake
      ninja-build
      autoconf
      libtool
      zlib1g-dev
      gcc
      g++

script:
  - . tools/setup_env.sh
  - tools/build_dependencies.py -j4
  - tools/bootstrap.py
  - ninja -j4 -C out
  - python tools/run_test.py
