language: cpp

compiler:
  - gcc
  - clang

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y ppa:smspillaz/cmake-2.8.12
  - sudo add-apt-repository -y ppa:beineri/opt-qt55
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get purge cmake
  - sudo apt-get install -y
      libgl1-mesa-dev
      qt55declarative
      zlib1g-dev
      python-mako
      cmake
      ninja-build
      gcc-4.8
      g++-4.8

script:
  - if [ $CC == gcc ]; then export CC=gcc-4.8; export CXX=g++-4.8; fi
  - . tools/setup_env.sh
  - tools/build_dependencies.py -j4 --shared --cc=$CC --cxx=$CXX
  - tools/bootstrap.py --cc=$CC --cxx=$CXX --qt5dir=/opt/qt55/lib/cmake -C Release
  - ninja -j4 -C out
  - cd out && ctest -VV
  - cd ${TRAVIS_BUILD_DIR} && tools/run_test.py
