language: cpp

compiler: gcc

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9 gcc-4.9 -qq ninja-build
  - sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev qttools5-dev-tools qtdeclarative5-dev-tools qt5-default qtdeclarative5-qtquick2-plugin qtdeclarative5-test-plugin
  - export CC="gcc-4.9"
  - export CXX="g++-4.9"

script: ./build.py -I deps/ubuntu.gypi
