language: cpp

compiler:
  - gcc
  - clang

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted"
  - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421 1E9377A2BA9EF27F 3B4FE6ACC0B21F32
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpango-1.0-0 qtbase5-dev qtdeclarative5-dev qttools5-dev-tools qtdeclarative5-dev-tools qt5-default qtdeclarative5-qtquick2-plugin qtdeclarative5-test-plugin ninja-build curl unzip cmake
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.9 g++-4.9; fi
  - if [ "$CC" = "gcc" ]; then export CC=gcc-4.9; export CXX=g++-4.9; export USE_CLANG=0; fi
  - if [ "$CC" = "clang" ]; then sudo apt-get install -qq clang-3.6; fi
  - if [ "$CC" = "clang" ]; then export CC=clang-3.6; export CXX=clang++-3.6; export PATH=/usr/lib/llvm-3.6/bin:"$PATH"; export USE_CLANG=1; fi

script:
  - build/download_dependency.py -j4
  - mkdir -p cmake_build && cd cmake_build && cmake -GNinja -DCMAKE_PREFIX_PATH=../build/deps ..
  - ninja -j4
  - ctest -VV
