sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - travis_wait travis_retry sudo add-apt-repository -y $QT_PPA
  - travis_wait travis_retry sudo apt-get update -qq
  - travis_wait travis_retry sudo apt-get install -y
      libgl1-mesa-dev
      ${QT}base
      ${QT}declarative
      zlib1g-dev
      python-virtualenv
      cmake
      ninja-build
  - virtualenv venv
  - . venv/bin/activate
  - pip install -r tools/requirements.txt
  - . /opt/${QT}/bin/${QT}-env.sh

script:
  - if [[ -n "$NO_GRPC" ]]; then DEPS_ARGS=--no-grpc ; fi
  - tools/build_dependencies.py -j4 --shared --cc=$CC --cxx=$CXX $DEPS_ARGS
  - tools/build_dependencies.py --clean
  - tools/build_dependencies.py -j4 --shared --debug --cc=$CC --cxx=$CXX $DEPS_ARGS
  - ${TRAVIS_BUILD_DIR}/tools/bootstrap.py --cc=$CC --cxx=$CXX --qt5dir=/opt/${QT}/lib/cmake
  - . ${TRAVIS_BUILD_DIR}/tools/setup_env.sh Debug
  - ninja -j4 -C ${TRAVIS_BUILD_DIR}/out/Debug
  - cd ${TRAVIS_BUILD_DIR}/out/Debug && ctest -VV
  - if [[ -z "$NO_GRPC" ]]; then cd ${TRAVIS_BUILD_DIR} && tools/run_test.py -C Debug ; fi
  - . ${TRAVIS_BUILD_DIR}/tools/setup_env.sh Release
  - ninja -j4 -C ${TRAVIS_BUILD_DIR}/out/Release
  - cd ${TRAVIS_BUILD_DIR}/out/Release && ctest -VV
  - if [[ -z "$NO_GRPC" ]]; then cd ${TRAVIS_BUILD_DIR} && tools/run_test.py -C Release ; fi

env:
  matrix:
    - QT=qt56
      QT_PPA=ppa:beineri/opt-qt562-trusty

    - QT=qt56
      QT_PPA=ppa:beineri/opt-qt562-trusty
      NO_GRPC=1

    - QT=qt57
      QT_PPA=ppa:beineri/opt-qt57-trusty

    - QT=qt55
      QT_PPA=ppa:beineri/opt-qt551-trusty
