sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y ppa:beineri/opt-qt55-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -y
      libgl1-mesa-dev
      qt55base
      qt55declarative
      zlib1g-dev
      python-virtualenv
      cmake
      ninja-build
  - virtualenv venv
  - . venv/bin/activate
  - pip install -r tools/requirements.txt

script:
  - tools/build_dependencies.py -j4 --shared --cc=$CC --cxx=$CXX
  - . /opt/qt55/bin/qt55-env.sh
  - ${TRAVIS_BUILD_DIR}/tools/bootstrap.py --cc=$CC --cxx=$CXX --qt5dir=/opt/qt55/lib/cmake
  - . ${TRAVIS_BUILD_DIR}/tools/setup_env.sh Debug
  - ninja -j4 -C ${TRAVIS_BUILD_DIR}/out/Debug
  - cd ${TRAVIS_BUILD_DIR}/out/Debug && ctest -VV
  - cd ${TRAVIS_BUILD_DIR} && tools/run_test.py -C Debug
  - . ${TRAVIS_BUILD_DIR}/tools/setup_env.sh Release
  - ninja -j4 -C ${TRAVIS_BUILD_DIR}/out/Release
  - cd ${TRAVIS_BUILD_DIR}/out/Release && ctest -VV
  - cd ${TRAVIS_BUILD_DIR} && tools/run_test.py -C Release
